Method,Name,Error,Occurrences
GET,/detail.html?id=zzz4f044-b040-410d-8ead-4de0446aec7e,"HTTPConnectionPool(host='39.100.0.61', port=30001): Max retries exceeded with url: /detail.html?id=zzz4f044-b040-410d-8ead-4de0446aec7e (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bc0e64ef0>: Failed to establish a new connection: [Errno 111] Connection refused'))",1
GET,/category.html,"HTTPConnectionPool(host='39.100.0.61', port=30001): Max retries exceeded with url: /category.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bc0e48828>: Failed to establish a new connection: [Errno 111] Connection refused'))",1
DELETE,/cart,"HTTPConnectionPool(host='39.100.0.61', port=30001): Max retries exceeded with url: /cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bc0592390>: Failed to establish a new connection: [Errno 110] Connection timed out'))",3
POST,/orders,"HTTPConnectionPool(host='39.100.0.61', port=30001): Max retries exceeded with url: /orders (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bc051aac8>: Failed to establish a new connection: [Errno 110] Connection timed out'))",3
POST,/orders,"HTTPConnectionPool(host='39.100.0.61', port=30001): Max retries exceeded with url: /orders (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bc0ed6e48>: Failed to establish a new connection: [Errno 111] Connection refused'))",5
POST,/cart,500 Server Error: Internal Server Error for url: http://39.100.0.61:30001/cart,38
GET,/catalogue,"HTTPConnectionPool(host='39.100.0.61', port=30001): Max retries exceeded with url: /catalogue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bc0ea34a8>: Failed to establish a new connection: [Errno 111] Connection refused'))",1
GET,/detail.html?id=837ab141-399e-4c1f-9abc-bace40296bac,"HTTPConnectionPool(host='39.100.0.61', port=30001): Max retries exceeded with url: /detail.html?id=837ab141-399e-4c1f-9abc-bace40296bac (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bc107bc88>: Failed to establish a new connection: [Errno 111] Connection refused'))",1
POST,/cart,"HTTPConnectionPool(host='39.100.0.61', port=30001): Max retries exceeded with url: /cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bc05cb7b8>: Failed to establish a new connection: [Errno 110] Connection timed out'))",3
GET,/login,"HTTPConnectionPool(host='39.100.0.61', port=30001): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bc108fa58>: Failed to establish a new connection: [Errno 110] Connection timed out'))",1
GET,/customers,"HTTPConnectionPool(host='39.100.0.61', port=30001): Max retries exceeded with url: /customers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bc0592198>: Failed to establish a new connection: [Errno 110] Connection timed out'))",1
GET,/detail.html?id=d3588630-ad8e-49df-bbd7-3167f7efb246,"HTTPConnectionPool(host='39.100.0.61', port=30001): Max retries exceeded with url: /detail.html?id=d3588630-ad8e-49df-bbd7-3167f7efb246 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bc0ebc240>: Failed to establish a new connection: [Errno 110] Connection timed out'))",3
GET,/customers,"HTTPConnectionPool(host='39.100.0.61', port=30001): Max retries exceeded with url: /customers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bc0f0ae80>: Failed to establish a new connection: [Errno 111] Connection refused'))",1
GET,/catalogue,"HTTPConnectionPool(host='39.100.0.61', port=30001): Max retries exceeded with url: /catalogue (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bc0c65400>: Failed to establish a new connection: [Errno 110] Connection timed out'))",34775
GET,/detail.html?id=03fef6ac-1896-4ce8-bd69-b798f85c6e0b,"HTTPConnectionPool(host='39.100.0.61', port=30001): Max retries exceeded with url: /detail.html?id=03fef6ac-1896-4ce8-bd69-b798f85c6e0b (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bc0cbaf28>: Failed to establish a new connection: [Errno 111] Connection refused'))",1
POST,/orders,406 Client Error: Not Acceptable for url: http://39.100.0.61:30001/orders,6353
GET,/category.html,"HTTPConnectionPool(host='39.100.0.61', port=30001): Max retries exceeded with url: /category.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bc05cb908>: Failed to establish a new connection: [Errno 110] Connection timed out'))",1
GET,/login,"HTTPConnectionPool(host='39.100.0.61', port=30001): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bc115a4a8>: Failed to establish a new connection: [Errno 111] Connection refused'))",1
POST,/orders,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))",2
GET,/basket.html,"HTTPConnectionPool(host='39.100.0.61', port=30001): Max retries exceeded with url: /basket.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bc05b7cf8>: Failed to establish a new connection: [Errno 110] Connection timed out'))",3
DELETE,/cart,"HTTPConnectionPool(host='39.100.0.61', port=30001): Max retries exceeded with url: /cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bc0f81160>: Failed to establish a new connection: [Errno 111] Connection refused'))",3
POST,/cart,"HTTPConnectionPool(host='39.100.0.61', port=30001): Max retries exceeded with url: /cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bc05deba8>: Failed to establish a new connection: [Errno 111] Connection refused'))",3
GET,/basket.html,"HTTPConnectionPool(host='39.100.0.61', port=30001): Max retries exceeded with url: /basket.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bc05e7ba8>: Failed to establish a new connection: [Errno 111] Connection refused'))",3
